const views=[...document.querySelectorAll(".view")];let current="boot",powered=true;
const show=id=>{views.forEach(v=>v.classList.toggle("hidden",v.id!==id));current=id;document.querySelector("#pageTitle").textContent=id==="home"?"Android VM":id[0].toUpperCase()+id.slice(1)};
setTimeout(()=>show("home"),1500);
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));
document.querySelector("#homeBtn").onclick=()=>show("home");
document.querySelector("#back").onclick=()=>show(current==="home"?"home":"home");
document.querySelector("#power").onclick=()=>{powered=!powered;show(powered?"home":"boot");if(powered)setTimeout(()=>show("home"),1000)};
document.querySelector("#vmPower").onclick=()=>document.querySelector("#power").click();
document.querySelector("#save").onclick=()=>{let n=document.querySelector("#deviceName").value;document.querySelector("#profileName").textContent=n||"Virtual Android";alert("Settings saved")};
document.querySelector("#browse").onclick=()=>{let u=document.querySelector("#url").value.trim();document.querySelector("#webbox").textContent=u?`Browser request prepared for: ${u}`:"Enter a URL first."};
document.querySelector("#run").onclick=()=>{let c=document.querySelector("#cmd").value.trim(),t=document.querySelector("#term");t.innerHTML+=`<br>$ ${c}`+(c==="help"?`<br>Commands: help, clear, version`:"");if(c==="version")t.innerHTML+="<br>Virtual Master Web 1.0.0";if(c==="clear")t.innerHTML="";document.querySelector("#cmd").value=""};
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");